# Generated by Django 2.2 on 2021-02-09 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(choices=[(None, 'select'), (1, 'Uttora'), (2, 'Dhanmondi'), (3, 'Boshundhora'), (4, 'Gulshan 1'), (5, 'Gulshan 2')])),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('washRoom', models.IntegerField(blank=True, default='', max_length=120, null=True)),
                ('bedRoom', models.IntegerField(blank=True, default='', max_length=120, null=True)),
                ('roadSize', models.IntegerField(blank=True, default='', max_length=120, null=True)),
                ('lift', models.IntegerField(choices=[(None, 'select'), (0, 'No Lift'), (1, 'Lift service available')])),
                ('floor', models.IntegerField(blank=True, default='', max_length=120, null=True)),
                ('price', models.IntegerField(blank=True, default='', max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(choices=[(None, 'select'), (1, 'Uttora'), (2, 'Dhanmondi'), (3, 'Boshundhora'), (4, 'Gulshan 1'), (5, 'Gulshan 2')])),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('washRoom', models.IntegerField(blank=True, default='', max_length=120, null=True)),
                ('bedRoom', models.IntegerField(blank=True, default='', max_length=120, null=True)),
                ('roadSize', models.IntegerField(blank=True, default='', max_length=120, null=True)),
                ('lift', models.IntegerField(choices=[(None, 'select'), (0, 'No Lift'), (1, 'Lift service available')])),
                ('floor', models.IntegerField(blank=True, default='', max_length=120, null=True)),
                ('price', models.IntegerField(blank=True, default='', max_length=120, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
