# Generated by Django 2.2 on 2021-02-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='bedRoom',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='lift',
            field=models.IntegerField(choices=[(None, 'select'), (0, 'No Lift'), (1, 'Lift service available')], default=1),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='roadSize',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='sqft',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='washRoom',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='bedRoom',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='lift',
            field=models.IntegerField(choices=[(None, 'select'), (0, 'No Lift'), (1, 'Lift service available')], default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='roadSize',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='sqft',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='washRoom',
            field=models.IntegerField(default=1),
        ),
    ]
