# Generated by Django 2.2 on 2021-02-09 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('location', models.CharField(choices=[('', 'Location'), ('Dhaka Cantonment', 'Dhaka Cantonment'), ('Dhamrai', 'Dhamrai'), ('Dhanmondi', 'Dhanmondi'), ('Gulshan 1', 'Gulshan 1'), ('Gulshan 2', 'Gulshan 2'), ('Jatrabari', 'Jatrabari'), ('Keraniganj', 'Keraniganj'), ('Khilgaon', 'Khilgaon'), ('Khilkhet', 'Khilkhet'), ('Lalbag', 'Lalbag'), ('Mohammadpur', 'Mohammadpur'), ('Mirpur', 'Mirpur'), ('Motijheel', 'Motijheel'), ('Palton', 'Palton'), ('Ramna', 'Ramna'), ('Sabujbag', 'Sabujbag'), ('Tejgaon', 'Tejgaon'), ('Uttara', 'Uttara'), ('Dhanmondi', 'Dhanmondi'), ('Boshundhora', 'Boshundhora'), ('Bonani', 'Bonani'), ('Mohakhali', 'mohakhali')], default='', max_length=120)),
                ('img1', models.ImageField(blank=True, default='demo.png', upload_to='images/post')),
                ('img2', models.ImageField(blank=True, default='demo.png', upload_to='images/post')),
                ('img3', models.ImageField(blank=True, default='demo.png', upload_to='images/post')),
                ('sqft', models.IntegerField()),
                ('washRoom', models.IntegerField()),
                ('bedRoom', models.IntegerField()),
                ('description', models.TextField(blank=True, default='', max_length=120, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('roadSize', models.IntegerField(blank=True, null=True)),
                ('lift', models.IntegerField(choices=[(None, 'select'), (0, 'No Lift'), (1, 'Lift service available')])),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtentionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='', max_length=120)),
                ('image', models.ImageField(blank=True, default='demo.png', upload_to='images/post')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
