# Generated by Django 2.2 on 2021-02-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='bedRoom',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='postad',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='postad',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='postad',
            name='roadSize',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='postad',
            name='sqft',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='postad',
            name='washRoom',
            field=models.IntegerField(default=1),
        ),
    ]
