# Generated by Django 2.2 on 2021-03-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210210_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='extentionuser',
            name='activation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extentionuser',
            name='code',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
