# Generated by Django 2.2 on 2021-03-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210302_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extentionuser',
            name='image',
            field=models.ImageField(blank=True, default='demo.png', upload_to='images/post/'),
        ),
        migrations.AlterField(
            model_name='postad',
            name='bedRoom',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='postad',
            name='floor',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='postad',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='postad',
            name='roadSize',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='postad',
            name='sqft',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='postad',
            name='washRoom',
            field=models.IntegerField(default=None),
        ),
    ]
